use crate::repo::get_file_at_ref;
use anyhow::Result;
use serde::{Deserialize, Serialize};
use std::path::PathBuf;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReviewMdComment {
    pub kind: String,
    #[serde(default)]
    pub title: Option<String>,
    pub body: String,
    #[serde(default)]
    pub file_path: Option<String>,
    #[serde(default)]
    pub line: Option<u32>,
    #[serde(default)]
    pub side: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WriteReviewMdArgs {
    pub repo_path: PathBuf,
    pub base_ref: String,
    pub head_ref: String,
    #[serde(default)]
    pub pr_title: Option<String>,
    pub comments: Vec<ReviewMdComment>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct SnippetLine {
    pub number: u32,
    pub text: String,
    pub is_target: bool,
}

struct RenderComment {
    title: Option<String>,
    body: String,
    file_path: Option<String>,
    line: Option<u32>,
    side: Option<String>,
    snippet: Vec<SnippetLine>,
}

/// 1-based target line; returns the target plus one neighbor on each side, clamped to file bounds.
pub fn snippet_around(content: &str, line: u32) -> Vec<SnippetLine> {
    let lines: Vec<&str> = content.lines().collect();
    if lines.is_empty() || line == 0 {
        return Vec::new();
    }
    let total = lines.len() as u32;
    let target = line.min(total);
    let start = if target <= 1 { 1 } else { target - 1 };
    let end = (target + 1).min(total);
    (start..=end)
        .map(|n| SnippetLine {
            number: n,
            text: lines[(n - 1) as usize].to_string(),
            is_target: n == target,
        })
        .collect()
}

fn render_review_md(pr_title: Option<&str>, comments: &[RenderComment]) -> String {
    let mut out = String::new();
    out.push_str("# Code Review\n\n");
    out.push_str(
        "> Generated by Guided Review. Each item below is a review comment to address.\n\n",
    );
    if let Some(title) = pr_title {
        if !title.is_empty() {
            out.push_str(&format!("**PR:** {title}\n\n"));
        }
    }

    let inline: Vec<&RenderComment> =
        comments.iter().filter(|c| c.file_path.is_some()).collect();
    let top: Vec<&RenderComment> =
        comments.iter().filter(|c| c.file_path.is_none()).collect();

    if !inline.is_empty() {
        out.push_str("## Inline comments\n\n");
        let mut files: Vec<&str> = Vec::new();
        for c in &inline {
            if let Some(f) = c.file_path.as_deref() {
                if !files.contains(&f) {
                    files.push(f);
                }
            }
        }
        for file in files {
            out.push_str(&format!("### {file}\n\n"));
            for c in inline.iter().filter(|c| c.file_path.as_deref() == Some(file)) {
                let loc = match (c.line, c.side.as_deref()) {
                    (Some(l), Some(s)) => format!("L{l} ({s})"),
                    (Some(l), None) => format!("L{l}"),
                    _ => "(file)".to_string(),
                };
                match c.title.as_deref() {
                    Some(t) if !t.is_empty() => {
                        out.push_str(&format!("- **{loc}** — {t}\n"))
                    }
                    _ => out.push_str(&format!("- **{loc}**\n")),
                }
                for bl in c.body.lines() {
                    out.push_str(&format!("  > {bl}\n"));
                }
                if !c.snippet.is_empty() {
                    out.push_str("\n  ```\n");
                    for sl in &c.snippet {
                        let marker = if sl.is_target { ">" } else { " " };
                        out.push_str(&format!("  {marker} {:>4}  {}\n", sl.number, sl.text));
                    }
                    out.push_str("  ```\n");
                }
                out.push('\n');
            }
        }
    }

    if !top.is_empty() {
        out.push_str("## General comments\n\n");
        for c in &top {
            if let Some(t) = c.title.as_deref() {
                if !t.is_empty() {
                    out.push_str(&format!("- **{t}**\n"));
                }
            }
            for bl in c.body.lines() {
                out.push_str(&format!("  > {bl}\n"));
            }
            out.push('\n');
        }
    }

    out
}

pub fn write_review_md(args: &WriteReviewMdArgs) -> Result<String> {
    let mut rendered: Vec<RenderComment> = Vec::new();
    for c in &args.comments {
        let snippet = match (c.file_path.as_deref(), c.line) {
            (Some(file), Some(line)) => {
                let refspec = if c.side.as_deref() == Some("LEFT") {
                    &args.base_ref
                } else {
                    &args.head_ref
                };
                match get_file_at_ref(&args.repo_path, file, refspec) {
                    Ok(Some(content)) => snippet_around(&content, line),
                    _ => Vec::new(),
                }
            }
            _ => Vec::new(),
        };
        rendered.push(RenderComment {
            title: c.title.clone(),
            body: c.body.clone(),
            file_path: c.file_path.clone(),
            line: c.line,
            side: c.side.clone(),
            snippet,
        });
    }

    let content = render_review_md(args.pr_title.as_deref(), &rendered);
    let path = args.repo_path.join("REVIEW.md");
    std::fs::write(&path, content)?;
    Ok(path.to_string_lossy().into_owned())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn snippet_around_centers_and_clamps() {
        let content = "one\ntwo\nthree\nfour";
        let mid = snippet_around(content, 2);
        assert_eq!(mid.len(), 3);
        assert_eq!(mid[0].number, 1);
        assert!(mid[1].is_target);
        assert_eq!(mid[1].text, "two");

        let first = snippet_around(content, 1);
        assert_eq!(first.len(), 2);
        assert!(first[0].is_target);

        let last = snippet_around(content, 4);
        assert_eq!(last.len(), 2);
        assert!(last[1].is_target);
        assert_eq!(last[1].text, "four");
    }

    #[test]
    fn render_groups_inline_by_file_and_lists_general() {
        let comments = vec![
            RenderComment {
                title: Some("Null check".to_string()),
                body: "Guard this.".to_string(),
                file_path: Some("src/a.ts".to_string()),
                line: Some(24),
                side: Some("RIGHT".to_string()),
                snippet: snippet_around("a\nb\nc", 2),
            },
            RenderComment {
                title: None,
                body: "Split the PR.".to_string(),
                file_path: None,
                line: None,
                side: None,
                snippet: Vec::new(),
            },
        ];
        let out = render_review_md(Some("My PR"), &comments);
        assert!(out.contains("**PR:** My PR"));
        assert!(out.contains("### src/a.ts"));
        assert!(out.contains("L24 (RIGHT)"));
        assert!(out.contains("Guard this."));
        assert!(out.contains("## General comments"));
        assert!(out.contains("Split the PR."));
    }

    #[test]
    fn render_handles_no_comments() {
        let out = render_review_md(None, &[]);
        assert!(out.contains("# Code Review"));
        assert!(!out.contains("## Inline comments"));
        assert!(!out.contains("## General comments"));
    }
}
